### ISSUE TITLE
点击基础图表跟混合图表出现 Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by janchengwang** [lin-xin/manage-system#1]
## 错误详情
`vue.common.js?e881:422 TypeError: Cannot read property 'toString' of undefined
    at new Watcher (eval at <anonymous> (http://localhost:8080/app.js:1:0), <anonymous>:2379:14)
    at initComputed (eval at <anonymous> (http://localhost:8080/app.js:1:0), <anonymous>:2708:21)
    at initState (eval at <anonymous> (http://localhost:8080/app.js:1:0), <anonymous>:2615:24)
    at VueComponent.Vue._init (eval at <anonymous> (http://localhost:8080/app.js:1:0), <anonymous>:3644:5)
    at new VueComponent (eval at <anonymous> (http://localhost:8080/app.js:1:0), <anonymous>:3810:12)
    at createComponentInstanceForVnode (eval at <anonymous> (http://localhost:8080/app.js:1:0), <anonymous>:2990:10)
    at init (eval at <anonymous> (http://localhost:8080/app.js:1:0), <anonymous>:3000:43)
    at createComponent (eval at <anonymous> (http://localhost:8080/app.js:1:0), <anonymous>:4527:9)
    at createElm (eval at <anonymous> (http://localhost:8080/app.js:1:0), <anonymous>:4470:9)
    at createChildren (eval at <anonymous> (http://localhost:8080/app.js:1:0), <anonymous>:4595:9)logError @ vue.common.js?e881:422`

**Comment by lin-xin** [comment]
Hi,@janchengwang
请问你是什么时候clone到本地的呢？可能是在之前我还没完成的时候会出现这种情况。我现在在本地运行正常。
你能尝试git pull更新一下吗？

**Comment by lin-xin** [comment]
@janchengwang 这是用的vue-echarts-v3插件的bug，目前已经修复好，需要重新npm install这个插件。
可以这样做：
`npm un vue-echarts-v3 -S`
卸载掉之后再：
`npm i vue-echarts-v3 -S`
就会安装最新的版本了
